const PT: Record<string, string> = {
  // Hosts
  'Brazil': 'Brasil',
  'Mexico': 'México',
  'Canada': 'Canadá',
  'USA': 'EUA',

  // América do Sul
  'Argentina': 'Argentina',
  'Uruguay': 'Uruguai',
  'Colombia': 'Colômbia',
  'Ecuador': 'Equador',
  'Chile': 'Chile',
  'Paraguay': 'Paraguai',
  'Bolivia': 'Bolívia',
  'Peru': 'Peru',
  'Venezuela': 'Venezuela',

  // América do Norte / Central / Caribe
  'Panama': 'Panamá',
  'Costa Rica': 'Costa Rica',
  'Honduras': 'Honduras',
  'Jamaica': 'Jamaica',
  'Curaçao': 'Curaçao',
  'Haiti': 'Haiti',
  'Trinidad and Tobago': 'Trinidad e Tobago',

  // Europa
  'Germany': 'Alemanha',
  'France': 'França',
  'Spain': 'Espanha',
  'Portugal': 'Portugal',
  'England': 'Inglaterra',
  'Netherlands': 'Países Baixos',
  'Italy': 'Itália',
  'Belgium': 'Bélgica',
  'Croatia': 'Croácia',
  'Switzerland': 'Suíça',
  'Austria': 'Áustria',
  'Sweden': 'Suécia',
  'Norway': 'Noruega',
  'Scotland': 'Escócia',
  'Poland': 'Polônia',
  'Serbia': 'Sérvia',
  'Turkey': 'Turquia',
  'Ukraine': 'Ucrânia',
  'Denmark': 'Dinamarca',
  'Greece': 'Grécia',
  'Romania': 'Romênia',
  'Hungary': 'Hungria',
  'Slovakia': 'Eslováquia',
  'Slovenia': 'Eslovênia',
  'Czech Republic': 'Tchéquia', // FIFA usa "Tchéquia" oficialmente desde 2016
  'Czechia': 'Tchéquia',
  'Wales': 'País de Gales',
  'Albania': 'Albânia',
  'Bosnia-Herzegovina': 'Bósnia-Herzegovina',
  'North Macedonia': 'Macedônia do Norte',
  'Iceland': 'Islândia',
  'Finland': 'Finlândia',

  // África
  'South Africa': 'África do Sul',
  'Morocco': 'Marrocos',
  'Senegal': 'Senegal',
  'Egypt': 'Egito',
  'Algeria': 'Argélia',
  'Tunisia': 'Tunísia',
  'Ivory Coast': 'Costa do Marfim',
  'Ghana': 'Gana',
  'Nigeria': 'Nigéria',
  'Cameroon': 'Camarões',
  'DR Congo': 'Congo (RDC)',
  'Cape Verde': 'Cabo Verde',
  'Mali': 'Mali',
  'Zambia': 'Zâmbia',
  'Tanzania': 'Tanzânia',
  'Zimbabwe': 'Zimbábue',
  'Comoros': 'Comores',
  'Kenya': 'Quênia',
  'Uganda': 'Uganda',

  // Ásia / Oceania
  'Japan': 'Japão',
  'South Korea': 'Coreia do Sul',
  'Australia': 'Austrália',
  'Saudi Arabia': 'Arábia Saudita',
  'Iran': 'Irã',
  'Iraq': 'Iraque',
  'Qatar': 'Catar',
  'Uzbekistan': 'Uzbequistão',
  'Jordan': 'Jordânia',
  'Indonesia': 'Indonésia',
  'New Zealand': 'Nova Zelândia',
  'China': 'China',
  'Thailand': 'Tailândia',
  'Bahrain': 'Bahrein',
  'Oman': 'Omã',
  'Kuwait': 'Kuwait',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  'Palestine': 'Palestina',
};

export function teamPt(name: string | null | undefined): string {
  if (!name) return '';
  return PT[name] ?? name;
}
